image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
   - node_modules/
    
stages:
  - build
  - deploy

build:
  image: mhart/alpine-node:11
  stage: build
  script:
   - yarn install
   - yarn test
   - CI=false yarn build
   - ls
   - ls -R build || true
   - ls dist || true
   - rm -rf public
   - mv build public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'

