image: mhart/alpine-node:11
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
   - node_modules/
    
stages:
  - build
  - deploy

build:
  stage: build
  script:
   - yarn install
   - CI=false yarn build
   - mv dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'

deploy:
  stage: deploy
  image: python:latest
  script:
  - pip install awscli
  - aws --endpoint-url https://s3.ir-thr-at1.arvanstorage.com s3 cp public s3://kaseb-module/dist --recursive
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "chat"'

